#pragma config(Sensor, dgtl1,  Touch_Sensor,   sensorTouch)
#pragma config(Motor,  port1,           M_Motor_Left,  tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          M_Motor_Right, tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//It takes 810 1Msec to move 1 tile (1 foot)
task main()
{
	while(vexRT[Btn8D] == 0)
	{
		wait1Msec(1);
	}

	if(vexRT[Btn8D]==1)
	{
		motor(M_Motor_Left) = 55;
		motor(M_Motor_Right) = 50;
		wait1Msec(2800);
		motor(M_Motor_Left) = 12;
		motor(M_Motor_Right) = 107;
		wait1Msec(2800);
		motor(M_Motor_Left) = 55;
		motor(M_Motor_Right) = 50;
		wait1Msec(3000);
	}
}
