#pragma config(Sensor, dgtl1,  Touch_Sensor,   sensorTouch)
#pragma config(Motor,  port1,           M_Motor_Left,  tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          M_Motor_Right, tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor(M_Motor_Left) = 63;
	motor(M_Motor_Right) = 50;
	wait1Msec(3000);
}

//Unused for now
//while(SensorValue(Touch_Sensor) == 0) {
//    wait1Msec(1);
//  }

//	if(SensorValue(Touch_Sensor)==1)
//	{
//		motor(M_Motor_Left) = 63;
//		motor(M_Motor_Right) = 60;
//		wait1Msec(500);
//	}
//}
